### ISSUE TITLE
Verifier model training

### ISSUE THREAD

**Issue by CownowAn** [thu-wyz/inference_scaling#1]
Thanks for the nice work and for sharing the code repo!
After checking the code repository, I noticed that the verifier model training code wasn't included.
Would it be possible for you to share the code for this part? It would be a huge help.

**Comment by thu-wyz** [comment]
We are also the same team of AIMO 2nd place winner, here is our AIMO repo https://github.com/AIMO-CMU-MATH/CMU_MATH-AIMO.git , you can find the verifier model training code there.
