### ISSUE TITLE
Problem with sampling baseline evaluation

### ISSUE THREAD

**Issue by zzjchen** [thu-wyz/inference_scaling#5]
Following your instructions, I'm able to run sampling and evaluate the results of major voting, weighted voting. However, I cannot modify the scripts/evaluate.sh to evaluate the Best-of-N sampling correctly.
I believe its something related to the "--agg_func" passed to math_evaluate.py.

**Comment by thu-wyz** [comment]
do not pass weighted, instead set --agg_fuct=last

**Comment by zzjchen** [comment]
Thanks I'll check it out
